[package]
name = "dsp_playground"
version = "0.1.0"
authors = ["actonDev <chris.actondev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[example]]
name = "biquadex"
path = "examples/biquadex/main.rs"